services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: adim
      POSTGRES_PASSWORD: adim
      POSTGRES_DB: adim
    ports:
      - "5432:5432"
  neo4j:
    image: neo4j:5.12
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password123
  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - ./qdrant_data:/qdrant/storage # Maps local folder to container storage
    ports:
      - "6333:6333"
      - "6334:6334"

  backend:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env  # This automatically loads your keys into the container
    depends_on:
      - db
      - neo4j
      - qdrant
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - NEO4J_URI=bolt://neo4j:7687